version: '3'

networks:
  default:
    name: "catalogo"
    external: true

services:
  api:
    container_name: catalogo-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app/
    depends_on:
      - db

  db:
    container_name: catalogo-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: catalogo

